<?php

namespace Database\Seeders;

use App\Models\Produit;
use Illuminate\Database\Seeder;

class ProduitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
     
    /**
     * Run the database seeds.
     */

    public function run(): void
    {
        Produit::insert(
            [
            [
                'nom' => 'Fauteuil Cuir Vintage',
                'description' => 'Fauteuil en cuir de style vintage, confortable et robuste.',
                'prix' => 349.00,
                'stock' => 12,
                'isPinned' => false,
                'ventes' => 5,
                'image1' => 'product_1.png',
                'image3' => 'product_1.png',
                'image4' => 'product_1.png',
                'image2' => 'product_1.png',
                'couleur' => 'Blanc',
                'produitscategorie_id' => 7,
                'user_id' => 1,
                'promo_id' => null,
                
            ],
            [
                'nom' => 'Chaise Scandinave Bois',
                'description' => 'Chaise légère en bois inspirée du design scandinave.',
                'prix' => 129.00,
                'stock' => 30,
                'isPinned' => false,
                'ventes' => 9,
                'image1' => 'product_2.png',
                'image3' => 'product_2.png',
                'image4' => 'product_2.png',
                'image2' => 'product_2.png',
                'couleur' => 'Noir',
                'produitscategorie_id' => 1,
                'user_id' => 1,
                'promo_id' => 2,
                
            ],
            [
                'nom' => 'Table Basse Industrielle',
                'description' => 'Table basse avec plateau en bois et pieds en métal.',
                'prix' => 199.00,
                'stock' => 8,
                'isPinned' => false,
                'ventes' => 16,
                'image1' => 'product_3.png',
                'image3' => 'product_3.png',
                'image4' => 'product_3.png',
                'image2' => 'product_3.png',
                'couleur' => 'Blanc',
                'produitscategorie_id' => 2,
                'user_id' => 1,
                'promo_id' => 3,
            ],
            [
                'nom' => 'Lampe Suspension Moderne',
                'description' => 'Lampe suspension pour salon, éclairage doux et design.',
                'prix' => 89.00,
                'stock' => 25,
                'isPinned' => false,
                'ventes' => 3,
                'image1' => 'product_4.png',
                'image3' => 'product_4.png',
                'image4' => 'product_4.png',
                'image2' => 'product_4.png',
                'couleur' => 'Noir',
                'produitscategorie_id' => 11,
                'user_id' => 1,
                'promo_id' => null,

            ],
            [
                'nom' => 'Bibliothèque Étagère Bois',
                'description' => 'Grande bibliothèque modulable pour bureau ou salon.',
                'prix' => 259.00,
                'stock' => 6,
                'isPinned' => false,
                'ventes' => 1,
                'image1' => 'product_5.png',
                'image3' => 'product_5.png',
                'image4' => 'product_5.png',
                'image2' => 'product_5.png',
                'couleur' => 'Blanc',
                'produitscategorie_id' => 5,
                'user_id' => 1,
                'promo_id' => 2,
            ],
            [
                'nom' => 'Pouff Chesterfield',
                'description' => 'Pouff confortable en tissu rare avec finitions soignées.',
                'prix' => 189.00,
                'stock' => 15,
                'isPinned' => false,
                'ventes' => 4,
                'image1' => 'product_6.png',
                'image3' => 'product_6.png',
                'image4' => 'product_6.png',
                'image2' => 'product_6.png',
                'couleur' => 'Noir',
                'produitscategorie_id' => 7,
                'user_id' => 1,
                'promo_id' => 3,

            ],
            [
                'nom' => 'Étagère Murale Design',
                'description' => 'Étagère murale moderne pour optimiser l\'espace.',
                'prix' => 79.00,
                'stock' => 20,
                'isPinned' => false,
                'ventes' => 29,
                'image1' => 'product_7.png',
                'image3' => 'product_7.png',
                'image4' => 'product_7.png',
                'image2' => 'product_7.png',
                'couleur' => 'Blanc',
                'produitscategorie_id' => 3,
                'user_id' => 1,
                'promo_id' => null,
                
            ],
            [
                'nom' => 'Fauteuil Rotin Naturel',
                'description' => 'Fauteuil en rotin tressé naturel, style bohème chic.',
                'prix' => 299.00,
                'stock' => 10,
                'isPinned' => false,
                'ventes' => 5,
                'image1' => 'product_8.png',
                'image3' => 'product_8.png',
                'image4' => 'product_8.png',
                'image2' => 'product_8.png',
                'couleur' => 'Noir',
                'produitscategorie_id' => 7,
                'user_id' => 1,
                'promo_id' => null,
                
            ],
            [
                'nom' => 'Chaise Bureau Moderne',
                'description' => 'Chaise de bureau ergonomique avec dossier réglable.',
                'prix' => 179.00,
                'stock' => 18,
                'isPinned' => false,
                'ventes' => 3,
                'image1' => 'product_9.png',
                'image3' => 'product_9.png',
                'image4' => 'product_9.png',
                'image2' => 'product_9.png',
                'couleur' => 'Blanc',
                'produitscategorie_id' => 1,
                'user_id' => 1,
                'promo_id' => 1,
                
            ],
            [
                'nom' => 'Canapé Bureau Moderne',
                'description' => 'Chaise de bureau ergonomique avec dossier réglable.',
                'prix' => 189.00,
                'stock' => 18,
                'isPinned' => false,
                'ventes' => 5,
                'image1' => 'feature_1.png',
                'image3' => 'feature_1.png',
                'image4' => 'feature_1.png',
                'image2' => 'feature_1.png',
                'couleur' => 'Blanc',
                'produitscategorie_id' => 1,
                'user_id' => 1,
                'promo_id' => null,
                
            ],
            [
                'nom' => 'Bureau Moderne',
                'description' => 'Chaise de bureau ergonomique avec dossier réglable.',
                'prix' => 169.00,
                'stock' => 18,
                'isPinned' => false,
                'ventes' => 9,
                'image1' => 'feature_2.png',
                'image3' => 'feature_2.png',
                'image4' => 'feature_2.png',
                'image2' => 'feature_2.png',
                'couleur' => 'Blanc',
                'produitscategorie_id' => 1,
                'user_id' => 1,
                'promo_id' => null,
                
            ],
            [
                'nom' => 'Fauteuil Bureau Moderne',
                'description' => 'Chaise de bureau ergonomique avec dossier réglable.',
                'prix' => 179.00,
                'stock' => 18,
                'isPinned' => false,
                'ventes' => 2,
                'image1' => 'feature_3.png',
                'image3' => 'feature_3.png',
                'image4' => 'feature_3.png',
                'image2' => 'feature_3.png',
                'couleur' => 'Blanc',
                'produitscategorie_id' => 1,
                'user_id' => 1,
                'promo_id' => null,
                
            ],
            [
                'nom' => 'Bibliotheque Bureau Moderne',
                'description' => 'Chaise de bureau ergonomique avec dossier réglable.',
                'prix' => 189.00,
                'stock' => 18,
                'isPinned' => false,
                'ventes' => 13,
                'image1' => 'feature_4.png',
                'image3' => 'feature_4.png',
                'image4' => 'feature_4.png',
                'image2' => 'feature_4.png',
                'couleur' => 'Blanc',
                'produitscategorie_id' => 1,
                'user_id' => 1,
                'promo_id' => null,
                
            ],
            [
                'nom' => 'Lampe Bureau Moderne',
                'description' => 'Chaise de bureau ergonomique avec dossier réglable.',
                'prix' => 169.00,
                'stock' => 18,
                'isPinned' => false,
                'ventes' => 18,
                'image1' => 'feature_4.png',
                'image3' => 'feature_4.png',
                'image4' => 'feature_4.png',
                'image2' => 'feature_4.png',
                'couleur' => 'Blanc',
                'produitscategorie_id' => 1,
                'user_id' => 1,
                'promo_id' => null,
                
            ],
            [
                'nom' => 'Chaise Bureau Moderne',
                'description' => 'Chaise de bureau ergonomique avec dossier réglable.',
                'prix' => 179.00,
                'stock' => 18,
                'isPinned' => false,
                'ventes' => 0,
                'image1' => 'banner_img.png',
                'image3' => 'banner_img.png',
                'image4' => 'banner_img.png',
                'image2' => 'banner_img.png',
                'couleur' => 'Blanc',
                'produitscategorie_id' => 1,
                'user_id' => 1,
                'promo_id' => null,
                
            ],
        ]); 

    }
}