<?php

namespace Database\Seeders;

use App\Models\Produit;
use Illuminate\Database\Seeder;

class ProduitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Produit::insert([
            [
                'nom' => 'Canapé Bleu Moderne',
                'description' => 'Canapé deux places au design contemporain avec structure métallique noire et coussins bleus confortables.',
                'prix' => 349.00,
                'stock' => 12,
                'isPinned' => true,
                'ventes' => 5,
                'image1' => 'banner_img.png',
                'image2' => 'banner_img.png',
                'image3' => 'banner_img.png',
                'image4' => 'banner_img.png',
                'couleur' => 'Bleu',
                'produitscategorie_id' => 7,
                'user_id' => 1,
                'promo_id' => null,
            ],
            [
                'nom' => 'Chaise Eames Scandinave Orange',
                'description' => 'Chaise iconique de style scandinave avec coque orange vif et pieds en bois naturel, design intemporel.',
                'prix' => 129.00,
                'stock' => 30,
                'isPinned' => false,
                'ventes' => 9,
                'image1' => 'product_2.png',
                'image2' => 'product_2.png',
                'image3' => 'product_2.png',
                'image4' => 'product_2.png',
                'couleur' => 'Orange',
                'produitscategorie_id' => 1,
                'user_id' => 1,
                'promo_id' => 2,
            ],
            [
                'nom' => 'Chaise Serie 7 Jaune',
                'description' => 'Chaise empilable au design minimaliste avec assise jaune moutarde et structure en bois courbé.',
                'prix' => 199.00,
                'stock' => 8,
                'isPinned' => true,
                'ventes' => 16,
                'image1' => 'product_3.png',
                'image2' => 'product_3.png',
                'image3' => 'product_3.png',
                'image4' => 'product_3.png',
                'couleur' => 'Jaune',
                'produitscategorie_id' => 2,
                'user_id' => 1,
                'promo_id' => 3,
            ],
            [
                'nom' => 'Chaise Eames Grise Patchwork',
                'description' => 'Chaise au design rétro avec revêtement patchwork gris et blanc, pieds en bois pour un look vintage moderne.',
                'prix' => 89.00,
                'stock' => 25,
                'isPinned' => true,
                'ventes' => 3,
                'image1' => 'product_4.png',
                'image2' => 'product_4.png',
                'image3' => 'product_4.png',
                'image4' => 'product_4.png',
                'couleur' => 'Gris',
                'produitscategorie_id' => 11,
                'user_id' => 1,
                'promo_id' => null,
            ],
            [
                'nom' => 'Chaise Eames Blanche',
                'description' => 'Chaise classique design scandinave avec coque blanche lisse et pieds croisés en bois naturel.',
                'prix' => 259.00,
                'stock' => 6,
                'isPinned' => false,
                'ventes' => 1,
                'image1' => 'product_5.png',
                'image2' => 'product_5.png',
                'image3' => 'product_5.png',
                'image4' => 'product_5.png',
                'couleur' => 'Blanc',
                'produitscategorie_id' => 5,
                'user_id' => 1,
                'promo_id' => 2,
            ],
            [
                'nom' => 'Chaise Eames Verte Olive',
                'description' => 'Chaise design moderne avec coque vert olive mat et pieds en bois, parfaite pour un intérieur naturel.',
                'prix' => 189.00,
                'stock' => 15,
                'isPinned' => false,
                'ventes' => 4,
                'image1' => 'product_6.png',
                'image2' => 'product_6.png',
                'image3' => 'product_6.png',
                'image4' => 'product_6.png',
                'couleur' => 'Vert',
                'produitscategorie_id' => 7,
                'user_id' => 1,
                'promo_id' => 3,
            ],
            [
                'nom' => 'Chaise Eames Beige',
                'description' => 'Chaise au design épuré avec coque beige crème et pieds en bois, idéale pour tout type d\'intérieur.',
                'prix' => 79.00,
                'stock' => 20,
                'isPinned' => false,
                'ventes' => 29,
                'image1' => 'product_7.png',
                'image2' => 'product_7.png',
                'image3' => 'product_7.png',
                'image4' => 'product_7.png',
                'couleur' => 'Beige',
                'produitscategorie_id' => 3,
                'user_id' => 1,
                'promo_id' => null,
            ],
            [
                'nom' => 'Chaise Eames Rouge',
                'description' => 'Chaise iconique avec coque rouge vif et pieds en bois, apporte une touche de couleur dynamique.',
                'prix' => 299.00,
                'stock' => 10,
                'isPinned' => false,
                'ventes' => 5,
                'image1' => 'product_8.png',
                'image2' => 'product_8.png',
                'image3' => 'product_8.png',
                'image4' => 'product_8.png',
                'couleur' => 'Rouge',
                'produitscategorie_id' => 7,
                'user_id' => 1,
                'promo_id' => null,
            ],
            [
                'nom' => 'Fauteuil Lounge Bois Courbé',
                'description' => 'Fauteuil design organique en bois courbé naturel, pièce sculpturale alliant confort et esthétique.',
                'prix' => 179.00,
                'stock' => 18,
                'isPinned' => false,
                'ventes' => 3,
                'image1' => 'product_9.png',
                'image2' => 'product_9.png',
                'image3' => 'product_9.png',
                'image4' => 'product_9.png',
                'couleur' => 'Bois naturel',
                'produitscategorie_id' => 1,
                'user_id' => 1,
                'promo_id' => 1,
            ],
            [
                'nom' => 'Fauteuil Accoudoirs Bleu Ciel',
                'description' => 'Fauteuil moderne avec accoudoirs enveloppants bleu ciel et pieds en bois, design contemporain confortable.',
                'prix' => 189.00,
                'stock' => 18,
                'isPinned' => false,
                'ventes' => 5,
                'image1' => 'feature_1.png',
                'image2' => 'feature_1.png',
                'image3' => 'feature_1.png',
                'image4' => 'feature_1.png',
                'couleur' => 'Bleu ciel',
                'produitscategorie_id' => 1,
                'user_id' => 1,
                'promo_id' => null,
            ],
            [
                'nom' => 'Chaise Eames Orange Vintage',
                'description' => 'Chaise design rétro avec coque orange éclatant et pieds en bois, parfaite pour un style vintage.',
                'prix' => 169.00,
                'stock' => 18,
                'isPinned' => false,
                'ventes' => 9,
                'image1' => 'feature_2.png',
                'image2' => 'feature_2.png',
                'image3' => 'feature_2.png',
                'image4' => 'feature_2.png',
                'couleur' => 'Orange',
                'produitscategorie_id' => 1,
                'user_id' => 1,
                'promo_id' => null,
            ],
            [
                'nom' => 'Fauteuil Rotin Tressé Naturel',
                'description' => 'Fauteuil en rotin tressé à la main avec forme arrondie, style bohème chic et écologique.',
                'prix' => 179.00,
                'stock' => 18,
                'isPinned' => false,
                'ventes' => 2,
                'image1' => 'feature_3.png',
                'image2' => 'feature_3.png',
                'image3' => 'feature_3.png',
                'image4' => 'feature_3.png',
                'couleur' => 'Naturel',
                'produitscategorie_id' => 1,
                'user_id' => 1,
                'promo_id' => null,
            ],
            [
                'nom' => 'Canapé Moutarde Vintage',
                'description' => 'Canapé deux places au style rétro années 60 avec tissu jaune moutarde et pieds inclinés en bois.',
                'prix' => 189.00,
                'stock' => 18,
                'isPinned' => false,
                'ventes' => 13,
                'image1' => 'feature_4.png',
                'image2' => 'feature_4.png',
                'image3' => 'feature_4.png',
                'image4' => 'feature_4.png',
                'couleur' => 'Moutarde',
                'produitscategorie_id' => 1,
                'user_id' => 1,
                'promo_id' => null,
            ],
            [
                'nom' => 'Pouf Capitonné Turquoise',
                'description' => 'Pouf rond capitonné avec revêtement en velours turquoise et détails de boutons, style élégant.',
                'prix' => 169.00,
                'stock' => 18,
                'isPinned' => false,
                'ventes' => 18,
                'image1' => 'offer_img.png',
                'image2' => 'offer_img.png',
                'image3' => 'offer_img.png',
                'image4' => 'offer_img.png',
                'couleur' => 'Turquoise',
                'produitscategorie_id' => 1,
                'user_id' => 1,
                'promo_id' => null,
            ],
            [
                'nom' => 'Lampe Suspendue Verte',
                'description' => 'Lampe suspension design moderne avec abat-jour vert pomme, apporte une touche de couleur lumineuse.',
                'prix' => 179.00,
                'stock' => 18,
                'isPinned' => false,
                'ventes' => 0,
                'image1' => 'product_1.png',
                'image2' => 'product_1.png',
                'image3' => 'product_1.png',
                'image4' => 'product_1.png',
                'couleur' => 'Vert',
                'produitscategorie_id' => 1,
                'user_id' => 1,
                'promo_id' => null,
            ],
        ]); 
    }
}